FROM node:18 AS builder

COPY ../frontend/ /frontend
WORKDIR /frontend

RUN npm install
RUN npm run build

# Deploy through Nginx
FROM nginx:stable-alpine
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# expose port here bruh
EXPOSE 80
RUN sudo ufw allow 80

CMD ["nginx", "-g", "daemon off;"]
